version: "3"
services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Movie
    volumes:
      movie-mysql: /var/lib/mysql
    ports:
      - "3306:3306"

  movie-api:
    image: image_movie:0.0.1-SNAPSHOT
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

volumes:
  movie-mysql: